/**
@license
*/

export const SELECT_PLAYER = 'SELECT_PLAYER';
export const SELECT_STARTER = 'SELECT_STARTER';
export const SELECT_STARTER_POSITION = 'SELECT_STARTER_POSITION';
export const APPLY_STARTER = 'APPLY_STARTER';
export const CANCEL_STARTER = 'CANCEL_STARTER';
