name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Archive test screenshots
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: test/integration/screenshots-current/
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: coverage/
